Solve MCMCChains break change
arviz-devs/ArviZ.jl pull request #77
Opened 2020-07-30 12:30 UTC by yiyuezhuo

fix #76

2020-07-30 13:17 UTC, yiyuezhuo commented
CI failed on `ValueError('Number of rows must be a positive integer, not 0')`, since `fig, _ = plt.subplots(0, 0, figsize=figsize, **backend_kwargs)` is invalid in current matplotlib version. It's a `ArviZ` bug and was fixed in recent commit:

https://github.com/arviz-devs/arviz/commit/29d4b13969a97c49584f103b3419feade9dea8bf

So [Job 363.4](https://travis-ci.com/github/arviz-devs/ArviZ.jl/jobs/366662593) passed, because it set `ARVIZ_VERSION=master` to use newest ArviZ code. I think that `ArviZ.jl` has nothing to do.

2020-07-30 13:41 UTC, ahartikainen commented
can you downgrade your matplotlib to 3.2?

    pip install "matplotlib==3.2"

2020-07-30 15:22 UTC, yiyuezhuo commented
If specified `ARVIZ_VERSION = 'master'`, `python -m pip install git+https://github.com/pydata/xarray git+https://github.com/arviz-devs/arviz` will be used to install `arviz`:

https://github.com/arviz-devs/ArviZ.jl/blob/master/.travis.yml#L56

Otherwise, it will install latest conda-forge version:

https://github.com/arviz-devs/ArviZ.jl/blob/master/src/ArviZ.jl#L96

2020-07-31 21:30 UTC, sethaxen commented
Thanks for the PR! ArviZ.jl has gotten a little out-of-sync with ArviZ due to my busy-ness (see #75 and #79). I'll open a few PRs to fix these errors/warnings then come back and review this one.

2020-08-26 01:07 UTC, yiyuezhuo commented
@sethaxen , `Turing@14.0` have been released, which use `MCMCChains@4.0.4`, so my MVE will fail as expected (in the release version) and this PR become useful I guess.

2020-09-05 22:10 UTC, sethaxen requested changes
Thanks for your patience! The approach looks right to me, and the test suite passes with Turing v0.13 and MCMCChains v3. I'm happy to approve once the following are handled:
- Bump compat of MCMCChains in `Project.toml` to v4 (I will bump docs compats in a subsequent PR) and test suite passes
- Format checker passes (see suggestion)
- Increment patch version number

2020-09-05 22:10 UTC, sethaxen commented on src/mcmcchains.jl
> +    loc_str_to_old = Dict(name_str => name_old for (name_str, name_old) in zip(loc_names, loc_names_old))
Suggestion from the new format checking action (https://github.com/arviz-devs/ArviZ.jl/pull/77/checks?check_run_id=1076393897#step:5:29)
```suggestion
    loc_str_to_old =
        Dict(name_str => name_old for (name_str, name_old) in zip(loc_names, loc_names_old))
```

2020-09-06 04:17 UTC, sethaxen commented on Project.toml
> +MCMCChains = "0.3.15, 0.4, 1.0, 2.0, 3.0"
This should do it
```suggestion
MCMCChains = "0.3.15, 0.4, 1.0, 2.0, 3.0, 4.0"
```

2020-09-06 04:29 UTC, yiyuezhuo commented on Project.toml
> +MCMCChains = "0.3.15, 0.4, 1.0, 2.0, 3.0"
I misread `0.4` as `4.0` :(

2020-09-06 05:20 UTC, sethaxen commented
Looks like MCMCChains v4 also removed the `sorted` keyword from `Chains(...)` (see https://github.com/TuringLang/MCMCChains.jl/pull/197)

2020-09-06 07:45 UTC, yiyuezhuo commented
> Looks like MCMCChains v4 also removed the `sorted` keyword from `Chains(...)` (see [TuringLang/MCMCChains.jl#197](https://github.com/TuringLang/MCMCChains.jl/pull/197))

It seems like that I used a wrong version to run local unit tests...

2020-09-06 08:02 UTC, sethaxen approved these changes
LGTM! Thanks again!

2020-09-06 08:02 UTC, merged